#!/usr/bin/env bash
# Regenerates scripts/buildtools/weak-gtk-symbols.h.
#
# The unified binary links the GTK/WebKit stack neither at build time nor as a
# startup dependency. This header is force-included into every cgo C/C++
# compilation on Linux (CGO_CFLAGS/CGO_CXXFLAGS, see linux-cgo-env.sh) and
# declares each stack symbol the webview backend references as WEAK via GNU
# top-level asm. The linker then emits ordinary PLT entries for the undefined
# weak symbols, and at runtime appwindow_linux.go dlopen()s WebKitGTK —
# publishing the whole dependency tree — before the first call.
#
# All referenced symbols are functions (verified via relocation types), so no
# eager data relocations are involved.
#
# Run after changing the pinned webview_go version:
#   bash scripts/buildtools/gen-webview-stubs.sh
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# Resolve the module directory for the version SELECTED by this build (from
# go.mod), not whatever happens to be newest in the shared module cache.
webview_mod="$(cd "${repo_root}" && go list -m -f '{{.Dir}}' github.com/webview/webview_go)"
if [[ -z "${webview_mod}" || ! -d "${webview_mod}" ]]; then
	echo "error: could not resolve webview_go module directory (run 'go mod download' first)" >&2
	exit 1
fi

mkdir -p "${HOME}/tmp"
work_dir="$(mktemp -d -p "${HOME}/tmp")"
trap 'rm -rf "${work_dir}"' EXIT

# Compile the backend with the same flags cgo uses, then list the stack
# symbols it references. Flags come from the repo's pkg-config setup.
# shellcheck disable=SC1091
source "${repo_root}/scripts/buildtools/linux-cgo-env.sh"
pkg_config_bin="${PKG_CONFIG:-pkg-config}"
if ! "${pkg_config_bin}" --exists gtk+-3.0 webkit2gtk-4.0 2>/dev/null; then
	echo "error: GTK/WebKit headers unavailable (pkg-config cannot see gtk+-3.0 + webkit2gtk)" >&2
	echo "       install the dev packages or set SI_APP_SYSROOT" >&2
	exit 1
fi

g++ -fPIC -DWEBVIEW_STATIC -DWEBVIEW_GTK -std=c++11 \
	-I"${webview_mod}/libs/webview/include" \
	$("${pkg_config_bin}" --cflags gtk+-3.0 webkit2gtk-4.0) \
	-c "${webview_mod}/webview.cc" -o "${work_dir}/webview.o"

# icon_linux.go calls this one directly.
extra_syms="gtk_window_set_default_icon_from_file"

{
	nm -u "${work_dir}/webview.o" | awk '{print $2}'
	echo "${extra_syms}"
} | grep -E '^(gtk|gdk|webkit|g_|jsc_)' | sort -u > "${work_dir}/syms"

{
	echo "// Code generated by scripts/buildtools/gen-webview-stubs.sh; DO NOT EDIT."
	echo "//"
	echo "// Weak-symbol declarations for the GTK/WebKit symbol family referenced by"
	echo "// webview_go's Linux backend. This header is force-included into every cgo"
	echo "// C/C++ compilation on Linux (CGO_CFLAGS/CGO_CXXFLAGS in linux-cgo-env.sh),"
	echo "// so the backend's undefined references to these symbols are emitted WEAK:"
	echo "// the linker creates ordinary PLT entries and the binary starts without"
	echo "// WebKitGTK, resolving the symbols at runtime when appwindow_linux.go"
	echo "// dlopen()s the library before the first call."
	echo "//"
	echo "// Together with the link-flag stripping in scripts/buildtools/pkg-config,"
	echo "// this keeps the unified binary free of any WebKitGTK startup dependency."
	echo "// See the generator script for details."
	echo ""
	echo "#if defined(__GNUC__) && defined(__linux__) && !defined(__ASSEMBLER__)"
	echo ""
	sed 's/^/__asm__(".weak /; s/$/");/' "${work_dir}/syms"
	echo ""
	echo "#endif"
} > "${repo_root}/scripts/buildtools/weak-gtk-symbols.h"

echo "generated ${repo_root}/scripts/buildtools/weak-gtk-symbols.h ($(wc -l < "${work_dir}/syms") symbols)"
