// Code generated by scripts/buildtools/gen-webview-stubs.sh; DO NOT EDIT.
//
// Weak-symbol declarations for the GTK/WebKit symbol family referenced by
// webview_go's Linux backend. This header is force-included into every cgo
// C/C++ compilation on Linux (CGO_CFLAGS/CGO_CXXFLAGS in linux-cgo-env.sh),
// so the backend's undefined references to these symbols are emitted WEAK:
// the linker creates ordinary PLT entries and the binary starts without
// WebKitGTK, resolving the symbols at runtime when appwindow_linux.go
// dlopen()s the library before the first call.
//
// Together with the link-flag stripping in scripts/buildtools/pkg-config,
// this keeps the unified binary free of any WebKitGTK startup dependency.
// See the generator script for details.

#if defined(__GNUC__) && defined(__linux__) && !defined(__ASSEMBLER__)

__asm__(".weak gdk_display_manager_get");
__asm__(".weak gdk_display_manager_get_default_display");
__asm__(".weak gdk_x11_display_get_type");
__asm__(".weak g_free");
__asm__(".weak g_idle_add_full");
__asm__(".weak g_signal_connect_data");
__asm__(".weak g_signal_handlers_disconnect_matched");
__asm__(".weak gtk_container_add");
__asm__(".weak gtk_container_get_type");
__asm__(".weak gtk_init_check");
__asm__(".weak gtk_main");
__asm__(".weak gtk_main_iteration");
__asm__(".weak gtk_main_quit");
__asm__(".weak gtk_widget_destroy");
__asm__(".weak gtk_widget_get_type");
__asm__(".weak gtk_widget_grab_focus");
__asm__(".weak gtk_widget_set_size_request");
__asm__(".weak gtk_widget_show");
__asm__(".weak gtk_widget_show_all");
__asm__(".weak gtk_window_close");
__asm__(".weak gtk_window_get_type");
__asm__(".weak gtk_window_new");
__asm__(".weak gtk_window_resize");
__asm__(".weak gtk_window_set_default_icon_from_file");
__asm__(".weak gtk_window_set_geometry_hints");
__asm__(".weak gtk_window_set_resizable");
__asm__(".weak gtk_window_set_title");
__asm__(".weak g_type_check_instance_cast");
__asm__(".weak g_type_check_instance_is_a");
__asm__(".weak jsc_value_to_string");
__asm__(".weak webkit_get_major_version");
__asm__(".weak webkit_get_minor_version");
__asm__(".weak webkit_javascript_result_get_js_value");
__asm__(".weak webkit_settings_set_enable_developer_extras");
__asm__(".weak webkit_settings_set_enable_write_console_messages_to_stdout");
__asm__(".weak webkit_settings_set_javascript_can_access_clipboard");
__asm__(".weak webkit_user_content_manager_add_script");
__asm__(".weak webkit_user_content_manager_register_script_message_handler");
__asm__(".weak webkit_user_script_new");
__asm__(".weak webkit_web_view_get_settings");
__asm__(".weak webkit_web_view_get_type");
__asm__(".weak webkit_web_view_get_user_content_manager");
__asm__(".weak webkit_web_view_load_html");
__asm__(".weak webkit_web_view_load_uri");
__asm__(".weak webkit_web_view_new");

#endif
